---
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: gammon.im
    type: PRIMARY
    zone: gammon.im
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: gammon-site
      match:
        path:
          prefix: /
name: gammon-site
region: ams
services:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: igrmk/gammon-site
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: gammon-site
    source_dir: /
